
name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - 'app-devops/**'

jobs:
  build:
    runs-on: ubuntu-20.04 
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
-
        name: Run Hadolint
        uses:hadolint/hadolint-action@3.1.0
        with
            dockerfile: Dockerfile        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:.app-devops/Docker"
          push: true
          tags: ${{ secrets.DOCKER}}/node-press:${{ github.run_number }}
